apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: jupyter
  name: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jupyter
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: jupyter
    spec:
      containers:
        - image: maximilianpichler/bdtb_jupyter:buildx-latest
          name: jupyter
          ports:
            - containerPort: 8888
          resources: {}
          volumeMounts:
            - mountPath: ~/projects/
              name: jupyter-claim0
      restartPolicy: Always
      volumes:
        - name: jupyter-claim0
          persistentVolumeClaim:
            claimName: jupyter-claim0
status: {}
