name: build our image

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login
        run: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - name: change Workdirectory
        run: cd ./Anaconda
      - name: build the image
        run: |
          docker buildx build --push \
          --platform linux/arm64,linux/arm,linux/amd64 \
          --tag maximilianpichler/anaconda:buildx-latest . 